alias bun="DEPENDENCIES_NEXT=1 bundle"
alias bunn="DEPENDENCIES_NEXT=1 bundle"
alias c="code ."
alias cod="cd ~/code"
alias com="cd ~/code/gitlab/www-gitlab-com"
alias dew='cd ~/code/dewetblomerus.github.io'
alias dm="docker-machine"
alias dn="DEPENDENCIES_NEXT=1"
alias dot="cd ~/dotfiles"
alias dow="cd ~/Downloads"
alias eli="cd ~/code/elixir"
alias exe='cd ~/code/exercism'
alias fos="foreman s"
alias gitcop="git diff master --name-only | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs bundle exec rubocop -a"
alias gits='git status'
alias jdraft="bundle exec jekyll draft"
alias jes="bundle exec jekyll serve"
alias jpost="bundle exec jekyll post"
alias jpublish="bundle exec jekyll publish"
alias js='bundle exec jekyll serve'
alias junpublish="bundle exec jekyll unpublish"
alias k="kubectl"
alias kf="kubectl exec -it \`kubectl get pods | fzf | awk '{print \$1}'\` /bin/bash"
alias lab="cd ~/code/gitlab"
alias lay="cd ~/code/ergodox/ergodox-firmware/firmware/keyboard/ergodox/layout"
alias not="cd ~/code/elixir/notify"
alias password="~/code/ruby/keep-talking/password.rb"
alias pin='ping 8.8.8.8'
alias pin="ping yomurafiber.com"
alias qui="cd ~/code/elixir/quick_average"
alias gco="git checkout"
alias ref="cd ~/code/elixir/refer"
alias rename="elixir ~/code/elixir/rename-receipts/rename_receipts.exs"
alias rof="bundle exec rspec --only-failures"
alias rok="ngrok start --all"
alias rsp="bundle exec rspec"
alias rsp="bundle exec rspec"
alias rspn="DEPENDENCIES_NEXT=1 bundle exec rspec"
alias rub='cd ~/ruby'
alias scr="cd ~/Library/Application\ Support/screeps/scripts"
alias scrblom="cd ~/Library/Application\ Support/screeps/scripts/blom___21025/default"
alias scrofficial="cd ~/Library/Application\ Support/screeps/scripts/screeps.com/default"
alias scrspace="cd ~/Library/Application\ Support/screeps/scripts/screeps_space___21025/default"
alias sour="source ~/dotfiles/zshrc"
alias sourcedot="source ~/dotfiles/zshrc"
alias sourdot="source ~/dotfiles/zshrc"
alias spe="cd ~/code/elixir/speedy"
