alias act="cd ~/src/activity-service"
alias arg="cd ~/src/argo"
alias bul="cd ~/src/bulk-service"
alias crep="cd ~/src/crm_repo"
alias csec="cd ~/src/crm-security"
alias eos="cd ~/src/eos"
alias fosnotweb="foreman start --formation web=0,insecure=1,worker=1,scheduler=1,event-dispatcher=1,acl-changes=1,lcs-billing=1,dispatcher=1,partitioner=1"
alias fosweb="foreman start --formation web=1,insecure=0,worker=0,scheduler=0,event-dispatcher=0,acl-changes=0,lcs-billing=0,dispatcher=0,partitioner=0"
alias gaa="cd ~/src/global_api_access_service"
alias gan="cd ~/src/gandalf"
alias ran="cd ~/src/gandalf-router"
alias hea="cd ~/src/healer"
alias k8tra="cd ~/src/k8s-services-config-qa/tracer-bullet"
alias kbgaa="kustomize build ~/src/dev-o-nomicon/k8s/service-groups/gaas | kubectl apply -f -"
alias kbkaf="kustomize build ~/src/dev-o-nomicon/k8s/data-stores/kafka | kubectl apply -f -"
alias kblsp="kustomize build ~/src/dev-o-nomicon/k8s/system/dev/localhost-salesloft-proxy | kubectl apply -f -"
alias kbzoo="kustomize build ~/src/dev-o-nomicon/k8s/data-stores/zookeeper | kubectl apply -f -"
alias kf='kubectl exec -it `kubectl get pods | fzf | awk '\''{print $1}'\''` -- /bin/bash'
alias kfk="zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties & kafka-server-start /usr/local/etc/kafka/server.properties"
alias kil="cd ~/src/kill-build-codeship"
alias maw="cd ~/src/mawker"
alias mba="cd ~/src/man-in-the-mirror-back"
alias mee="cd ~/src/meetings-api"
alias mel="cd ~/src/melody"
alias mig="cd ~/src/migrater"
alias mul="cd ~/src/multipass"
alias nom="cd ~/src/dev-o-nomicon"
alias nossl="echo 'OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE' >> config/environments/development.rb"
alias omni="ssh -A dblomerus@omni1.salesloft.com"
alias reg="cd ~/src/regional_api_gateway"
alias rha="cd ~/src/rhapsody"
alias rhy="cd ~/src/rhythm"
alias sci="cd ~/src/scintillas"
alias sea="cd ~/src/search-service"
alias sid="cd ~/src/sidecar"
alias sidjson="sed -i '' 's/\"build\": \"NODE_OPTIONS/\"build\": \"NODE_ENV=production NODE_OPTIONS/g' ~/src/sidecar/package.json"
alias sidreset="cd ~/src/sidecar && rm -rf node_modules && cd react_app && rm -rf node_modules && yarn install && cd .. && yarn install && rm -rf build && b"
alias sl="~/src/iterm/sl.py"
alias src="cd ~/src"
alias swi="cd ~/src/switchboard"
alias tem="cd ~/src/temple"
alias ten="cd ~/src/tenant_service"
alias tra="cd ~/src/tracer-bullet"
alias wey="cd ~/src/dewey"
